### PR TITLE
[WIP] Fixes most of the performance issues, corrects tab/pages handling.

### PR DESCRIPTION
**Pull request by rockon999**
This is a WIP merge request as some features are broken or need cleanup.

Also, this depends on my other pull request.

What it does:

- Switches the app to Android's native view paging/tab handling to avoid spawning new activities which slow down the app and create a laggy user experience.
- Fixes issues with the list/recycler views that caused laggy scrolling.
- Switches the splash screen to only appear during app loading per Google's specs, the spinner should be the visual indication while data is loading in-app.
- Initial work on maintaining app state.
- Moved some assets around for compatibility's sake.
- Some more general cleanup.

What is broken/not perfect:
- Opening up the info activity for eateries is broken because it was using a global click handler (I think), need to switch that to be specific to the view so that it can function in the fragment properly.
- Search is current broken, I have to implement the cross-fragment system for that.
  - There is a static variable controlling part of search and that is partially why some things are weird. Need to de-static that variable.
- Cross-fragment data passing is currently not very clean albeit functional, needs cleanup.
- While the data is loading we need to ensure that users cannot attempt to open activities depending on the data, in other words making the spinner's behavior encompass the app.
- The spinner should probably be the branding color.
- The splash screen doesn't have the appdev logo.

### CODE REVIEW

**Comment by young-k** [comment]
Will review this after the other one gets merged

**Comment by rockon999** [comment]
Regression identified: "days of the week" are not sorted as offsets are, so the algorithm needed a slight tweak to show upcoming start times 100% correctly.

**Comment by rockon999** [comment]
Regression identified: some cafes use hardcoded day ranges, this code was impacted by the cleanup. While parsing, we now convert these into actual dates for the upcoming week.

**Comment by rockon999** [comment]
Closing.

**Pull request closed without merging**
